### ISSUE TITLE
Errors while starting via docker-compose

### ISSUE THREAD

**Issue by cmendesce** [kbastani/twitter-graph-analytics#10]
I tried to up and run the application via `docker-compose up` and I got a some erros and the application didn't go up. I tried in an Ubuntu Server 16 on Azure Cloud. 

Config module is running in a loop and the log is this:

```
config                  | 2016-10-30 12:23:30.250 DEBUG 1 --- [nfoReplicator-0] o.springframework.cloud.util.InetUtils   : Testing interface: eth0
config                  | 2016-10-30 12:23:30.250 DEBUG 1 --- [nfoReplicator-0] o.springframework.cloud.util.InetUtils   : Found non-loopback interface: eth0
config                  | 2016-10-30 12:23:30.260 DEBUG 1 --- [           main] s.c.c.d.h.DiscoveryClientHealthIndicator : Discovery Client has been initialized
config                  | 2016-10-30 12:23:30.350  INFO 1 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8888 (http)
config                  | 2016-10-30 12:23:30.351  INFO 1 --- [           main] c.n.e.EurekaDiscoveryClientConfiguration : Updating port to 8888
config                  | 2016-10-30 12:23:30.353  INFO 1 --- [           main] org.kbastani.ConfigServiceApplication    : Started ConfigServiceApplication in 45.615 seconds (JVM running for 46.865)
config                  | 2016-10-30 12:23:33.246  INFO 1 --- [nfoReplicator-0] o.a.http.impl.client.DefaultHttpClient   : I/O exception (java.net.NoRouteToHostException) caught when connecting to {}->http://172.17.0.8:8761: No route to host
config                  | 2016-10-30 12:23:33.246  INFO 1 --- [nfoReplicator-0] o.a.http.impl.client.DefaultHttpClient   : Retrying connect to {}->http://172.17.0.8:8761
config                  | 2016-10-30 12:23:36.318  INFO 1 --- [nfoReplicator-0] o.a.http.impl.client.DefaultHttpClient   : I/O exception (java.net.NoRouteToHostException) caught when connecting to {}->http://172.17.0.8:8761: No route to host
```

Dashboard module is logging this:

```
dashboard               | java.lang.AbstractMethodError: ch.qos.logback.classic.pattern.EnsureExceptionHandling.process(Lch/qos/logback/core/Context;Lch/qos/logback/core/pattern/Converter;)V
dashboard               |   at ch.qos.logback.core.pattern.PatternLayoutBase.start(PatternLayoutBase.java:85)
dashboard               |   at ch.qos.logback.classic.encoder.PatternLayoutEncoder.start(PatternLayoutEncoder.java:28)
dashboard               |   at ch.qos.logback.classic.BasicConfigurator.configure(BasicConfigurator.java:50)
dashboard               |   at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:164)
dashboard               |   at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
dashboard               |   at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
dashboard               |   at org.slf4j.LoggerFactory.bind(LoggerFactory.java:140)
dashboard               |   at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:119)
dashboard               |   at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:328)
dashboard               |   at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:280)
dashboard               |   at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
dashboard               |   at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
dashboard               |   at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
dashboard               |   at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:191)
dashboard               |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:1124)
dashboard               |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:1113)
dashboard               |   at org.kbastani.RankingDashboardApplication.main(RankingDashboardApplication.java:11)
dashboard               |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dashboard               |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
dashboard               |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dashboard               |   at java.lang.reflect.Method.invoke(Method.java:498)
dashboard               |   at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
dashboard               |   at java.lang.Thread.run(Thread.java:745)
```

And Crawler this:

```
crawler                 | java.lang.NoSuchMethodError: ch.qos.logback.core.util.Loader.getResourceOccurrenceCount(Ljava/lang/String;Ljava/lang/ClassLoader;)Ljava/util/Set;
crawler                 |   at ch.qos.logback.classic.util.ContextInitializer.multiplicityWarning(ContextInitializer.java:173)
crawler                 |   at ch.qos.logback.classic.util.ContextInitializer.statusOnResourceSearch(ContextInitializer.java:196)
crawler                 |   at ch.qos.logback.classic.util.ContextInitializer.getResource(ContextInitializer.java:143)
crawler                 |   at ch.qos.logback.classic.util.ContextInitializer.findURLOfDefaultConfigurationFile(ContextInitializer.java:137)
crawler                 |   at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
crawler                 |   at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
crawler                 |   at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
crawler                 |   at org.slf4j.LoggerFactory.bind(LoggerFactory.java:140)
crawler                 |   at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:119)
crawler                 |   at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:328)
crawler                 |   at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:280)
crawler                 |   at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
crawler                 |   at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
crawler                 |   at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
crawler                 |   at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:191)
crawler                 |   at org.springframework.boot.builder.SpringApplicationBuilder.createSpringApplication(SpringApplicationBuilder.java:99)
crawler                 |   at org.springframework.boot.builder.SpringApplicationBuilder.<init>(SpringApplicationBuilder.java:87)
crawler                 |   at org.kbastani.TwitterCrawlerApplication.main(TwitterCrawlerApplication.java:21)
crawler                 |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
crawler                 |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
crawler                 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
crawler                 |   at java.lang.reflect.Method.invoke(Method.java:498)
crawler                 |   at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
crawler                 |   at java.lang.Thread.run(Thread.java:745)
```

Finally, the Eureka page is showing this message:
`EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING INSTANCES ARE UP WHEN THEY'RE NOT. RENEWALS ARE LESSER THAN THRESHOLD AND HENCE THE INSTANCES ARE NOT BEING EXPIRED JUST TO BE SAFE.`

Is there a tip to fix these problems? I thing it is a little config or detail that I didn't get. 

Thanks in advance.

**Comment by cmendesce** [comment]
Hi. I got a solution for all these problems. The first one was related with the IP chosen by docker-machine in MacOS. I changed the fixed IP to **_192.168.99.100**_, that is the default for docker and cia in Mac. The two last problems were resolved just updating the version from **_1.3.1.RELEASE**_ to **_1.3.4.RELEASE**_ of `spring-boot-starter-parent` in the parent `pom.xml`. I got the ideia in this [link](https://github.com/spring-projects/spring-boot/issues/5304)

**Comment by kbastani** [comment]
Thanks for providing a solution to the issue. I will mark this for fix and if you would be kind enough to provide a pull request that would help others who run into the same problem.
